In [3]:
import numpy as np
import pandas as pd
from scipy import stats

In [4]:

df = pd.read_csv('winequality-red.csv', sep = ";")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [5]:
df.describe()


fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [40]:
def normalize(wine):
    result = wine.copy()
    for feature_name in wine.columns:
        max_value = wine[feature_name].max()
        min_value = wine[feature_name].min()
        result[feature_name] = (wine[feature_name] - min_value) / (max_value - min_value)
    return result
    
red=normalize(df)

red.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.247788          0.397260         0.00        0.068493   0.106845   
1       0.283186          0.520548         0.00        0.116438   0.143573   
2       0.283186          0.438356         0.04        0.095890   0.133556   
3       0.584071          0.109589         0.56        0.068493   0.105175   
4       0.247788          0.397260         0.00        0.068493   0.106845   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.140845              0.098940  0.567548  0.606299   0.137725   
1             0.338028              0.215548  0.494126  0.362205   0.209581   
2             0.197183              0.169611  0.508811  0.409449   0.191617   
3             0.225352              0.190813  0.582232  0.330709   0.149701   
4             0.140845              0.098940  0.567548  0.606299   0.137725   

    alcohol  quality  
0  0.153846      0.4  
1  0.215385      0.4  
2  0.215385      0.4  
3  0.215385      0.6  
4  0.153846      0.4

In [106]:
red.shape

(1599, 12)

In [141]:
red['quality'].unique()

array([0.4, 0.6, 0.8, 0.2, 1. , 0. ])

In [107]:
df.iloc[1, :-1].to_numpy()

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ])

In [108]:
checked_quality = df.loc[1, 'quality']
checked_quality

5

In [109]:
values = df.values
values

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [110]:
df[list(df.columns.values)[:-1]].to_numpy()

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [111]:
qualities = df['quality'].to_numpy()
qualities

array([5, 5, 5, ..., 6, 5, 6])

In [112]:
q_len = qualities.__len__()
q_len

1599

In [113]:
qualities_array = np.zeros((11, q_len), dtype=int)
qualities_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [114]:
counter = 0
for row in qualities_array:
    quality = qualities[counter]
    row[quality] = 1
    counter += 1

qualities_array[3][6]


1

In [115]:
i = 0
for index, row in df.iterrows():
    df.at[index, 'id'] = i
    i += 1

df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality   id  
0      9.4        5  0.0  
1      9.8        5  1.0  
2      9.8        5  2.0  
3      9.8        6  3.0  
4      9.4        5  4.0

In [116]:
df.drop(columns=['id'], inplace=True)

In [117]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [118]:

len(df)

1599

In [119]:
df['quality'].value_counts()


5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [120]:
df['quality'].nunique()

6

In [121]:
np.amin(df['quality'].values)

3

In [122]:
df.columns.to_list()[-1]

'quality'

In [123]:
type(df)

pandas.core.frame.DataFrame

In [124]:
aggs = df.groupby('quality').agg(['mean', 'std'])
aggs

fixed acidity           volatile acidity           citric acid  \
                 mean       std             mean       std        mean   
quality                                                                  
3            8.360000  1.770875         0.884500  0.331256    0.171000   
4            7.779245  1.626624         0.693962  0.220110    0.174151   
5            8.167254  1.563988         0.577041  0.164801    0.243686   
6            8.347179  1.797849         0.497484  0.160962    0.273824   
7            8.872362  1.992483         0.403920  0.145224    0.375176   
8            8.566667  2.119656         0.423333  0.144914    0.391111   

                  residual sugar           chlorides            ...  \
              std           mean       std      mean       std  ...   
quality                                                         ...   
3        0.250664       2.635000  1.401596  0.122500  0.066241  ...   
4        0.201030       2.694340  1.789436  0.090679  0.076192  ...   
5        0.180003       2.528855  1.359753  0.092736  0.053707  ...   
6        0.195108       2.477194  1.441576  0.084956  0.039563  ...   
7        0.194432       2.720603  1.371509  0.076588  0.029456  ...   
8        0.199526       2.577778  1.295038  0.068444  0.011678  ...   

        total sulfur dioxide              density                  pH  \
                        mean        std      mean       std      mean   
quality                                                                 
3                  24.900000  16.828877  0.997464  0.002002  3.398000   
4                  36.245283  27.583374  0.996542  0.001575  3.381509   
5                  56.513950  36.993116  0.997104  0.001589  3.304949   
6                  40.869906  25.038250  0.996615  0.002000  3.318072   
7                  35.020101  33.191206  0.996104  0.002176  3.290754   
8                  33.444444  25.433240  0.995212  0.002378  3.267222   

                  sulphates              alcohol            
              std      mean       std       mean       std  
quality                                                     
3        0.144052  0.570000  0.122020   9.955000  0.818009  
4        0.181441  0.596415  0.239391  10.265094  0.934776  
5        0.150618  0.620969  0.171062   9.899706  0.736521  
6        0.153995  0.675329  0.158650  10.629519  1.049639  
7        0.150101  0.741256  0.135639  11.465913  0.961933  
8        0.200640  0.767778  0.115379  12.094444  1.224011  

[6 rows x 22 columns]

In [125]:

# P(A|C) - for single example (with distinct feature from distinct group)
def cond_prob(row, feature, group):
    mu = aggs[feature]['mean'][group] # mean
    std = aggs[feature]['std'][group] # standard deviation

    # one selected observation (sigle value)
    sel_obs = df.iloc[row][feature]

    prob = stats.norm.pdf(sel_obs, loc=mu, scale=std)

    return prob
    



In [126]:
def predict_class(row):
    classes = []

    min_class = np.amin(df['quality'].values)
    max_class = np.amax(df['quality'].values)

    for group in range(min_class, max_class):
        # P(C)
        prob = len(df[df['quality'] == group])/len(df.index)
        for feature in df.columns:
            if feature == 'quality': break
            # P(C) * P(A|C)
            prob *= cond_prob(row, feature, group)
        classes.append(prob)
    return np.argmax(classes) + min_class # from what number classes starts
    

In [127]:
row = 1401
df.iloc[row]

fixed acidity             7.9000
volatile acidity          0.6900
citric acid               0.2100
residual sugar            2.1000
chlorides                 0.0800
free sulfur dioxide      33.0000
total sulfur dioxide    141.0000
density                   0.9962
pH                        3.2500
sulphates                 0.5100
alcohol                   9.9000
quality                   5.0000
Name: 1401, dtype: float64

In [128]:
predict_class(row)

5

In [129]:
training_df = df.sample(frac=0.4)
test_df = df.drop(training_df.index)

In [130]:
training_df.info()
training_df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 640 entries, 382 to 1146
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         640 non-null    float64
 1   volatile acidity      640 non-null    float64
 2   citric acid           640 non-null    float64
 3   residual sugar        640 non-null    float64
 4   chlorides             640 non-null    float64
 5   free sulfur dioxide   640 non-null    float64
 6   total sulfur dioxide  640 non-null    float64
 7   density               640 non-null    float64
 8   pH                    640 non-null    float64
 9   sulphates             640 non-null    float64
 10  alcohol               640 non-null    float64
 11  quality               640 non-null    int64  
dtypes: float64(11), int64(1)
memory usage: 65.0 KB


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
382             8.3              0.26         0.42            2.00      0.080   
999             6.4              0.69         0.00            1.65      0.055   
1583            6.2              0.46         0.29            2.10      0.074   
1280            7.1              0.46         0.20            1.90      0.077   
1456            6.0              0.54         0.06            1.80      0.050   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
382                  11.0                  27.0  0.99740  3.21       0.80   
999                   7.0                  12.0  0.99162  3.47       0.53   
1583                 32.0                  98.0  0.99578  3.33       0.62   
1280                 28.0                  54.0  0.99560  3.37       0.64   
1456                 38.0                  89.0  0.99236  3.30       0.50   

      alcohol  quality  
382      9.40        6  
999     12.90        6  
1583     9.80        5  
1280    10.40        6  
1456    10.55        6

In [131]:
test_df.info()
test_df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 959 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         959 non-null    float64
 1   volatile acidity      959 non-null    float64
 2   citric acid           959 non-null    float64
 3   residual sugar        959 non-null    float64
 4   chlorides             959 non-null    float64
 5   free sulfur dioxide   959 non-null    float64
 6   total sulfur dioxide  959 non-null    float64
 7   density               959 non-null    float64
 8   pH                    959 non-null    float64
 9   sulphates             959 non-null    float64
 10  alcohol               959 non-null    float64
 11  quality               959 non-null    int64  
dtypes: float64(11), int64(1)
memory usage: 97.4 KB


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
6            7.9              0.60         0.06             1.6      0.069   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
6                 15.0                  59.0   0.9964  3.30       0.46   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
6      9.4        5

In [132]:
check_df = test_df


In [133]:
check_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
6            7.9              0.60         0.06             1.6      0.069   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
6                 15.0                  59.0   0.9964  3.30       0.46   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
6      9.4        5

In [134]:
check_df = test_df.assign(quality=None)
check_df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
6            7.9              0.60         0.06             1.6      0.069   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
6                 15.0                  59.0   0.9964  3.30       0.46   

   alcohol quality  
0      9.4    None  
1      9.8    None  
2      9.8    None  
3      9.8    None  
6      9.4    None

In [135]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, train_size=0.8)
train_df.head()



fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
46             7.7             0.935         0.43             2.2      0.114   
78             6.7             0.750         0.12             2.0      0.086   
842           10.6             0.500         0.45             2.6      0.119   
872            7.3             0.350         0.24             2.0      0.067   
205           12.8             0.300         0.74             2.6      0.095   

     free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
46                  22.0                 114.0  0.99700  3.25       0.73   
78                  12.0                  80.0  0.99580  3.38       0.52   
842                 34.0                  68.0  0.99708  3.23       0.72   
872                 28.0                  48.0  0.99576  3.43       0.54   
205                  9.0                  28.0  0.99940  3.20       0.77   

     alcohol  quality  
46       9.2        5  
78      10.1        5  
842     10.9        6  
872     10.0        4  
205     10.8        7

In [136]:
for index, row in df.iterrows():
    print(index, row)

0 fixed acidity            7.4000
volatile acidity         0.7000
citric acid              0.0000
residual sugar           1.9000
chlorides                0.0760
free sulfur dioxide     11.0000
total sulfur dioxide    34.0000
density                  0.9978
pH                       3.5100
sulphates                0.5600
alcohol                  9.4000
quality                  5.0000
Name: 0, dtype: float64
1 fixed acidity            7.8000
volatile acidity         0.8800
citric acid              0.0000
residual sugar           2.6000
chlorides                0.0980
free sulfur dioxide     25.0000
total sulfur dioxide    67.0000
density                  0.9968
pH                       3.2000
sulphates                0.6800
alcohol                  9.8000
quality                  5.0000
Name: 1, dtype: float64
2 fixed acidity            7.800
volatile acidity         0.760
citric acid              0.040
residual sugar           2.300
chlorides                0.092
free sulfur dioxide    

In [137]:
df.iloc[1, :]

fixed acidity            7.8000
volatile acidity         0.8800
citric acid              0.0000
residual sugar           2.6000
chlorides                0.0980
free sulfur dioxide     25.0000
total sulfur dioxide    67.0000
density                  0.9968
pH                       3.2000
sulphates                0.6800
alcohol                  9.8000
quality                  5.0000
Name: 1, dtype: float64

In [138]:
df['alcohol'].tolist()

[9.4,
 9.8,
 9.8,
 9.8,
 9.4,
 9.4,
 9.4,
 10.0,
 9.5,
 10.5,
 9.2,
 10.5,
 9.9,
 9.1,
 9.2,
 9.2,
 10.5,
 9.3,
 9.0,
 9.2,
 9.4,
 9.7,
 9.5,
 9.4,
 9.7,
 9.3,
 9.5,
 9.5,
 9.4,
 9.8,
 10.1,
 10.6,
 9.8,
 9.4,
 9.2,
 9.6,
 10.8,
 9.7,
 9.8,
 10.5,
 10.5,
 9.3,
 10.5,
 10.3,
 9.5,
 13.1,
 9.2,
 9.5,
 9.2,
 9.2,
 9.2,
 9.4,
 9.4,
 9.4,
 10.2,
 9.5,
 9.6,
 9.4,
 10.0,
 9.4,
 9.2,
 9.3,
 9.5,
 9.8,
 10.9,
 10.9,
 9.6,
 10.7,
 10.7,
 10.5,
 9.5,
 9.5,
 9.5,
 9.2,
 9.6,
 10.5,
 10.5,
 10.7,
 10.1,
 9.1,
 9.2,
 9.4,
 9.1,
 9.4,
 10.3,
 10.1,
 9.9,
 9.6,
 9.5,
 9.0,
 9.5,
 9.9,
 9.8,
 9.6,
 10.5,
 12.9,
 10.7,
 9.2,
 9.8,
 9.0,
 10.2,
 10.4,
 9.0,
 9.2,
 9.4,
 9.2,
 9.3,
 9.3,
 9.6,
 9.3,
 9.5,
 9.8,
 9.8,
 9.7,
 9.5,
 10.5,
 10.0,
 9.4,
 10.9,
 9.2,
 9.0,
 10.9,
 9.2,
 9.5,
 9.5,
 9.4,
 10.9,
 10.9,
 10.5,
 9.4,
 9.4,
 13.0,
 13.0,
 9.8,
 9.9,
 9.6,
 9.5,
 9.2,
 9.5,
 9.5,
 9.6,
 9.5,
 14.0,
 9.4,
 14.0,
 9.4,
 10.0,
 9.3,
 10.2,
 10.5,
 10.3,
 9.4,
 10.1,
 10.1,
 10.5,
 10.5,
 10.5,
 10.5,
 